old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        new_webhook:
            connection:       default
            exchange_options: { name: 'tj.v1.new_webhook', type: direct }
    consumers:
        new_webhook:
            connection:       default
            exchange_options: { name: 'tj.v1.new_webhook', type: direct }
            queue_options:    { name: 'tj.v1.new_webhook'}
            callback:         App\Consumer\TjNewWebhookConsumer
